services:
  localstack:
    extends:
      service: localstack
      file: docker-compose.yaml
  app:
    # This is the app service, which is the main service of the application.
    # Access it at http://localhost:3000
    container_name: 'app'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - apps/server/.env
    environment:
      - DYNAMODB_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_REGION=ap-south-1
      - NODE_ENV=test
    depends_on:
      - localstack
    links:
      - localstack
