services:
  localstack:
    # This is the LocalStack service, which is a mock AWS environment.
    # Access it at http://localhost:4566
    container_name: 'aws-localstack'
    image: localstack/localstack
    ports:
      - '127.0.0.1:4566:4566' # LocalStack Gateway
      - '127.0.0.1:4510-4559:4510-4559' # external services port range
      - '127.0.0.1:443:443' # LocalStack HTTPS Gateway (Pro)
    environment:
      - DEBUG=${DEBUG:-1}
      - PERSISTENCE=${PERSISTENCE-}
      - ENABLE_CONFIG_UPDATES=1
    volumes:
      - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
  dynamodb_admin:
    # This is the dynamodb-admin service, which is a web-based UI for DynamoDB.
    # Access it at http://localhost:8001
    container_name: 'dynamodb-admin'
    image: aaronshaf/dynamodb-admin
    ports:
      - '8001:8001'
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
      - AWS_REGION=ap-south-1
    depends_on:
      - localstack